# Generated by Django 5.0.1 on 2024-01-06 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='all_resturant/%Y/%m/%d')),
                ('resturant', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('logo', models.ImageField(blank=True, upload_to='logo/%Y/%m/%d')),
                ('website', models.URLField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Discounted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_resturant', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='discounted/%Y/%m/%d')),
                ('discounted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Favourite1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Writer_fav/5%Y/%m/%d')),
                ('heading', models.CharField(max_length=50)),
                ('writeUp', models.CharField(max_length=1000)),
                ('writer', models.CharField(blank=True, max_length=50)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Writer_fav/5%Y/%m/%d')),
                ('heading', models.CharField(max_length=50)),
                ('writeUp', models.CharField(max_length=1000)),
                ('writer', models.CharField(blank=True, max_length=50)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='featured_dish/%Y/%m/%d')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hero/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='paid_hero1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='hero_for_all/%Y/%m/%d')),
                ('resturant', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='paid_hero2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='hero_for_all/%Y/%m/%d')),
                ('resturant', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='paid_hero3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='hero_for_all/%Y/%m/%d')),
                ('resturant', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='paid_spotlight1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='hero_for_all/%Y/%m/%d')),
                ('resturant', models.CharField(blank=True, max_length=1000)),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularRestaurantsView1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popuralar_1/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularRestaurantsView2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popuralar_2/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularRestaurantsView3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popuralar_3/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularRestaurantsView4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='popuralar_4/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchbyFood1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='most_ordered1/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='SearchbyFood2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='most_ordered2/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='SearchbyFood3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='most_ordered3/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='SearchbyFood4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='most_ordered4/%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='SearchbyFood5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='most_ordered/5%Y/%m/%d')),
                ('dish', models.CharField(blank=True, max_length=1000)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='https://example.com/default-image.jpg', upload_to='Writer_fav/5%Y/%m/%d')),
                ('heading', models.CharField(max_length=50)),
                ('writeUp', models.CharField(max_length=1000)),
                ('writer', models.CharField(blank=True, max_length=50)),
                ('url_to_dish', models.URLField(default='https://www.google.com')),
            ],
        ),
    ]
