# Generated by Django 5.0.1 on 2024-01-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_writer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='chefspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chef/5%Y/%m/%d')),
                ('heading', models.CharField(max_length=50)),
                ('writeUp', models.CharField(max_length=1000)),
                ('writer', models.CharField(blank=True, max_length=50)),
                ('url_to_dish', models.URLField(default='https://www.linkedin.com/in/sundayefeterry/')),
            ],
        ),
        migrations.DeleteModel(
            name='Favourite1',
        ),
        migrations.DeleteModel(
            name='Favourite2',
        ),
        migrations.AlterField(
            model_name='searchbyfood1',
            name='url_to_dish',
            field=models.URLField(default='https://www.linkedin.com/in/sundayefeterry/'),
        ),
        migrations.AlterField(
            model_name='searchbyfood2',
            name='url_to_dish',
            field=models.URLField(default='https://www.linkedin.com/in/sundayefeterry/'),
        ),
        migrations.AlterField(
            model_name='searchbyfood3',
            name='url_to_dish',
            field=models.URLField(default='https://www.linkedin.com/in/sundayefeterry/'),
        ),
        migrations.AlterField(
            model_name='searchbyfood4',
            name='url_to_dish',
            field=models.URLField(default='https://www.linkedin.com/in/sundayefeterry/'),
        ),
        migrations.AlterField(
            model_name='searchbyfood5',
            name='url_to_dish',
            field=models.URLField(default='https://www.linkedin.com/in/sundayefeterry/'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='url_to_dish',
            field=models.URLField(default='https://www.linkedin.com/in/sundayefeterry/'),
        ),
    ]
