# Generated by Django 5.0.1 on 2024-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='phone_number',
        ),
    ]
